### ISSUE TITLE
레파지토리 생성

### ISSUE THREAD

**Issue by SeokHoChoi** [HelloTutor/HelloTutor-F#2]
- [x] 저장소 생성
- [x] 저장소 프로젝트 이관
- [x] 이 이슈 연결하고 완료 처리 해보기.
- [x] 시작일, 완료일, 완료 목표일자 입력

**Comment by zero2080** [comment]
이슈를 닫아 주세요~
`Done` 상태는 이슈가 닫혀야 합니다.
자동화 되기 전 까지는 신경써 주세요~
